# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\x0csmart_office\"]\n\x10\x44iscoveryMessage\x12\x13\n\x0b\x64\x65vice_type\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\x12\x0e\n\x06\x61\x63tive\x18\x05 \x01(\x08\"\xa0\x01\n\rDeviceRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12?\n\nparameters\x18\x03 \x03(\x0b\x32+.smart_office.DeviceRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\">\n\x0e\x44\x65viceResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x9f\x01\n\nSensorData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65vice_type\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x30\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\".smart_office.SensorData.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"s\n\rGatewayReport\x12-\n\x0bsensor_data\x18\x01 \x03(\x0b\x32\x18.smart_office.SensorData\x12\x33\n\rdevice_states\x18\x02 \x03(\x0b\x32\x1c.smart_office.DeviceResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEVICEREQUEST_PARAMETERSENTRY._options = None
  _DEVICEREQUEST_PARAMETERSENTRY._serialized_options = b'8\001'
  _SENSORDATA_DATAENTRY._options = None
  _SENSORDATA_DATAENTRY._serialized_options = b'8\001'
  _DISCOVERYMESSAGE._serialized_start=30
  _DISCOVERYMESSAGE._serialized_end=123
  _DEVICEREQUEST._serialized_start=126
  _DEVICEREQUEST._serialized_end=286
  _DEVICEREQUEST_PARAMETERSENTRY._serialized_start=237
  _DEVICEREQUEST_PARAMETERSENTRY._serialized_end=286
  _DEVICERESPONSE._serialized_start=288
  _DEVICERESPONSE._serialized_end=350
  _SENSORDATA._serialized_start=353
  _SENSORDATA._serialized_end=512
  _SENSORDATA_DATAENTRY._serialized_start=469
  _SENSORDATA_DATAENTRY._serialized_end=512
  _GATEWAYREPORT._serialized_start=514
  _GATEWAYREPORT._serialized_end=629
# @@protoc_insertion_point(module_scope)
