# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: smart_devices.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'smart_devices.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13smart_devices.proto\x12\rsmart_devices\"\x81\x01\n\x0bSmartDevice\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x03 \x01(\t\x12\r\n\x05is_on\x18\x04 \x01(\x08\x12\x11\n\tdevice_ip\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65vice_port\x18\x06 \x01(\x05\"K\n\x04Lamp\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\r\n\x05is_on\x18\x02 \x01(\x08\x12\x12\n\nbrightness\x18\x03 \x01(\x02\x12\r\n\x05\x63olor\x18\x04 \x01(\t\"\xcb\x01\n\rDeviceCommand\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x12\n\nbrightness\x18\x03 \x01(\x02\x12\r\n\x05\x63olor\x18\x04 \x01(\t\x12@\n\nparameters\x18\x05 \x03(\x0b\x32,.smart_devices.DeviceCommand.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"3\n\x0f\x43ommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xc1\x01\n\x0f\x44\x65viceDiscovery\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x03 \x01(\t\x12\r\n\x05is_on\x18\x04 \x01(\x08\x12\x12\n\nbrightness\x18\x05 \x01(\x02\x12\r\n\x05\x63olor\x18\x06 \x01(\t\x12\x11\n\tdevice_ip\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65vice_port\x18\x08 \x01(\x05\x12\x17\n\x0fmotion_detected\x18\t \x01(\x08\x32\xb4\x01\n\x12SmartDeviceService\x12K\n\x0bSendCommand\x12\x1c.smart_devices.DeviceCommand\x1a\x1e.smart_devices.CommandResponse\x12Q\n\x0f\x44iscoverDevices\x12\x1e.smart_devices.DeviceDiscovery\x1a\x1e.smart_devices.CommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smart_devices_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICECOMMAND_PARAMETERSENTRY']._loaded_options = None
  _globals['_DEVICECOMMAND_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_SMARTDEVICE']._serialized_start=39
  _globals['_SMARTDEVICE']._serialized_end=168
  _globals['_LAMP']._serialized_start=170
  _globals['_LAMP']._serialized_end=245
  _globals['_DEVICECOMMAND']._serialized_start=248
  _globals['_DEVICECOMMAND']._serialized_end=451
  _globals['_DEVICECOMMAND_PARAMETERSENTRY']._serialized_start=402
  _globals['_DEVICECOMMAND_PARAMETERSENTRY']._serialized_end=451
  _globals['_COMMANDRESPONSE']._serialized_start=453
  _globals['_COMMANDRESPONSE']._serialized_end=504
  _globals['_DEVICEDISCOVERY']._serialized_start=507
  _globals['_DEVICEDISCOVERY']._serialized_end=700
  _globals['_SMARTDEVICESERVICE']._serialized_start=703
  _globals['_SMARTDEVICESERVICE']._serialized_end=883
# @@protoc_insertion_point(module_scope)
